### ISSUE TITLE
Update READMEs

### ISSUE THREAD

**Issue by atisharma** [dsummersl/sn2md#1]
Thank you for this great tool.

The README on github could do with an example of how to use the `-t` option to specify a template (I had to look at the code)

**Comment by dsummersl** [comment]
👍 I'll add that, and update with some documentation about the toml configuration before this next release - I've got some other template additions I'm adding support for too...stay tuned!

**Comment by dsummersl** [comment]
Closing this ticket:
- added changelog
- updated the readme to reflect the removed `-t` switch, the configuration file support and `--config` option.
