### ISSUE TITLE
Consider config file

### ISSUE THREAD

**Issue by atisharma** [dsummersl/sn2md#2]
It would be very useful to be able to set various things in a toml file. For example,

- setting the openAI API key instead of using the `OPENAI_API_KEY` env variable
- overriding `TO_MARKDOWN_TEMPLATE` (for example, I'd like to automatically add hashtag/keywords)

I can generate a pull request if you like.

**Comment by dsummersl** [comment]
great ideas, happy to accept a PR.

**Comment by dsummersl** [comment]
I'm working on a few more features - if you hoven't already started a PR for this, I'm happy to include this as well, just let me know!

**Comment by atisharma** [comment]
Hi, I'm working on it literally as I type. Nearly done, should be less than an hour.

While we're both here, I suggest removing langchain and using OpenAI's `openai` package directly. Langchain has a lot of dependencies and in your case, is just wrapping OpenAI's package in any case. I can do that while I have everything open, if that's OK.

**Comment by dsummersl** [comment]
no problem - I'll stay out of your way then! (I'm mostly wanting to add more supernote-tools support and unit tests - links/keywords/etc). I'm open to cutting langchain out, as you say for something as simple as this probably fine to call the APIs directly (I don't foresee any agent-ish behavior happening with this!).

**Comment by dsummersl** [comment]
(I'll have time to review this evening, thx for the PRs!)
